services:
  flaskapp:
    build: .
    container_name: rupeevault
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - bankdata_volume:/bankdata
    depends_on:
      - smtp
    networks:
      - appnet

  smtp:
    image: rnwood/smtp4dev
    container_name: smtp_server
    ports:
      - "1025:25"      # SMTP listening port
      - "3000:80"      # Web UI to view emails
    volumes:
      - smtp4dev_volume:/smtp4dev
    networks:
      - appnet

networks:
  appnet:

volumes:
  smtp4dev_volume:
  bankdata_volume: