version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: your_production_secret
      JWT_SECRET_KEY: your_jwt_secret_key
      production: 1
      # Use internal Docker hostname
      DATABASE_URI: mysql+pymysql://root:root@db:3306/flask_bank
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_bank
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
